services:
  - type: web
    name: velloc-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
